### ISSUE TITLE
Unable to make chips scrollable on a single line

### ISSUE THREAD

**Issue by larrytech7** [adroitandroid/ChipCloud#12]
I wish to be able to configure chips so that when in overflow, it could be scrollable and occupy just a single line. At the moment i don't see any configuration allowing such a behavior

**Comment by adroitandroid** [comment]
What do you mean by when in overflow? If you require chips in a single
line, you can achieve using a recyclerview itself

**Comment by larrytech7** [comment]
what I'm trying to achieve is a list of tags like with the Google playstore
.any links as to how such a recyclerview should be implemented?

**Comment by adroitandroid** [comment]
Set the layout manager for the recyclerview as a LinearLayoutManager with
horizontal orientation, check the constructor. Individual chips will be
your list items, so create the wrapcontent layout of them and use it in
onCreateViewHolder of your adapter. Should work fine 👌
